version: '3'
services:
  wasm:
    image: wasm:latest
    container_name: wasm
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:80
      ASPNETCORE_ENVIRONMENT: Development
    restart: on-failure
    # network_mode: host
    ports:
      # - 0.0.0.0:41234:41234
      # - 0.0.0.0:41234:41234/udp
      - 8082:80
    # volumes:
    #   - /home/pi/docker/volumes/wasm:/app/data
  
