version: '2.2'
services:
  openhab:
    image: openhab/openhab:milestone
    container_name: openhab3
    restart: always
    network_mode: host
    volumes:
      - /home/pi/docker/volumes/openhab/addons:/openhab/addons
      - /home/pi/docker/volumes/openhab/conf:/openhab/conf
      - /home/pi/docker/volumes/openhab/userdata:/openhab/userdata
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
    
