version: '3'
services:
  api:
    image: api:latest
    container_name: api
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:5000
      ASPNETCORE_ENVIRONMENT: Development
    restart: on-failure
    # network_mode: host
    ports:
      # - 0.0.0.0:41234:41234
      # - 0.0.0.0:41234:41234/udp
      - 8081:5000
    volumes:
      - /home/pi/docker/volumes/api:/app/data
  
