version: "3"
services:
  mariadb:
    image: jsurf/rpi-mariadb:latest
    container_name: mariadb
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: mariadbKla87Sie57
        MYSQL_DATABASE: mybb
        MYSQL_USER: mybb
        MYSQL_PASSWORD: mariadbKla87Sie57
    ports:
      - '3306:3306'
    volumes:
      - /home/pi/docker/volumes/mariadb:/var/lib/mysql