version: '3'
services:
  mqtt:
    image: eclipse-mosquitto
    restart: always
    container_name: mosquitto
    user: root:root
    expose:
        - "1883"
        - "8883"
        - "9001"
    ports:
        - "1883:1883"
        - "8883:8883"
        - "9001:9001"
    volumes:
      - /home/pi/docker/volumes/mosquitto/config:/mosquitto/config
      - /etc/letsencrypt/archive/hmopi.dynv6.net/:/cert
      - /home/pi/docker/volumes/mosquitto/log:/mosquitto/log
      - /home/pi/docker/volumes/mosquitto/data:/mosquitto/data
      - /etc/localtime:/etc/localtime:ro
